version: "3.9"
services:
  gateway:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - phpbb
      - database
    volumes:
      - html:/var/www/html/:ro
  phpbb:
    build: ./php/
    restart: always
    expose:
      - "9000"
    depends_on:
      - database
    volumes:
      - html:/var/www/html/
  database:
    image: postgres:alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
volumes:
  html:
